apiVersion: v1
kind: ConfigMap
metadata:
  name: ovasabi-config
  labels:
    app: ovasabi-app
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  FEATURE_FLAGS: "{{ .Values.featureFlags | default "" }}" 