apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ovasabi-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers: "X-Platform-Metadata: {{ .Values.platformMetadata | default "" }}";
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - { { .Values.ingress.host | quote } }
      secretName: ovasabi-tls
  rules:
    - host: { { .Values.ingress.host | quote } }
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wasm-frontend
                port:
                  number: 8081
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ovasabi-app
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: ws-gateway
                port:
                  number: 8090
