apiVersion: v1
kind: Service
metadata:
  name: media-streaming
  labels:
    app: media-streaming
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: media-streaming
