apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  type: { { .Values.nexus.service.type } }
  ports:
    - port: { { .Values.nexus.service.port } }
      targetPort: { { .Values.nexus.service.port } }
  selector:
    app: nexus
