apiVersion: v1
kind: Service
metadata:
  name: ovasabi-app
  labels:
    app: ovasabi-app
spec:
  type: { { .Values.service.type } }
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ovasabi-app
