apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovasabi-app
  labels:
    app: ovasabi-app
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: ovasabi-app
  template:
    metadata:
      labels:
        app: ovasabi-app
    spec:
      containers:
        - name: ovasabi-app
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.port } }
          resources: { { - toYaml .Values.resources | nindent 12 } }
          envFrom:
            - configMapRef:
                name: ovasabi-config
            - secretRef:
                name: ovasabi-secrets
          affinity: { { - toYaml .Values.affinity | nindent 12 } }
          tolerations: { { - toYaml .Values.tolerations | nindent 12 } }
          nodeSelector: { { - toYaml .Values.nodeSelector | nindent 12 } }
