apiVersion: v1
kind: Service
metadata:
  name: ovasabi-app
  labels:
    app: ovasabi-app
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
  selector:
    app: ovasabi-app
