apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-frontend
  labels:
    app: wasm-frontend
spec:
  replicas: { { .Values.wasmFrontend.replicaCount } }
  selector:
    matchLabels:
      app: wasm-frontend
  template:
    metadata:
      labels:
        app: wasm-frontend
    spec:
      containers:
        - name: wasm-frontend
          image: '{{ .Values.wasmFrontend.image.repository }}:{{ .Values.wasmFrontend.image.tag }}'
          imagePullPolicy: { { .Values.wasmFrontend.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.wasmFrontend.service.port } }
          resources: { { - toYaml .Values.resources | nindent 12 } }
          envFrom:
            - configMapRef:
                name: ovasabi-config
            - secretRef:
                name: ovasabi-secrets
          affinity: { { - toYaml .Values.affinity | nindent 12 } }
          tolerations: { { - toYaml .Values.tolerations | nindent 12 } }
          nodeSelector: { { - toYaml .Values.nodeSelector | nindent 12 } }
