apiVersion: v1
kind: Service
metadata:
  name: wasm-frontend
  labels:
    app: wasm-frontend
spec:
  type: { { .Values.wasmFrontend.service.type } }
  ports:
    - port: 8100
      targetPort: 8100
  selector:
    app: wasm-frontend
