apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-gateway
  template:
    metadata:
      labels:
        app: ws-gateway
    spec:
      containers:
        - name: ws-gateway
          image: ws-gateway:latest # Update with your image registry if needed
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: NEXUS_GRPC_ADDR
              value: "nexus:50052"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
