apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "jaeger-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.0.0
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
    editable: true 