// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: api/protos/i18n/v0/i18n.proto

package i18n

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Translation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MasterId      int32                  `protobuf:"varint,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Flexible, JSONB-like
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Translation) Reset() {
	*x = Translation{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Translation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation) ProtoMessage() {}

func (x *Translation) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation.ProtoReflect.Descriptor instead.
func (*Translation) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{0}
}

func (x *Translation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Translation) GetMasterId() int32 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *Translation) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *Translation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Translation) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Translation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Translation) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Translation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTranslationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      int32                  `protobuf:"varint,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranslationRequest) Reset() {
	*x = CreateTranslationRequest{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranslationRequest) ProtoMessage() {}

func (x *CreateTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranslationRequest.ProtoReflect.Descriptor instead.
func (*CreateTranslationRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTranslationRequest) GetMasterId() int32 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *CreateTranslationRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CreateTranslationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateTranslationRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateTranslationRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateTranslationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   *Translation           `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranslationResponse) Reset() {
	*x = CreateTranslationResponse{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranslationResponse) ProtoMessage() {}

func (x *CreateTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranslationResponse.ProtoReflect.Descriptor instead.
func (*CreateTranslationResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTranslationResponse) GetTranslation() *Translation {
	if x != nil {
		return x.Translation
	}
	return nil
}

func (x *CreateTranslationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTranslationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TranslationId int32                  `protobuf:"varint,1,opt,name=translation_id,json=translationId,proto3" json:"translation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationRequest) Reset() {
	*x = GetTranslationRequest{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationRequest) ProtoMessage() {}

func (x *GetTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationRequest.ProtoReflect.Descriptor instead.
func (*GetTranslationRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{3}
}

func (x *GetTranslationRequest) GetTranslationId() int32 {
	if x != nil {
		return x.TranslationId
	}
	return 0
}

type GetTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   *Translation           `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationResponse) Reset() {
	*x = GetTranslationResponse{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationResponse) ProtoMessage() {}

func (x *GetTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationResponse.ProtoReflect.Descriptor instead.
func (*GetTranslationResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{4}
}

func (x *GetTranslationResponse) GetTranslation() *Translation {
	if x != nil {
		return x.Translation
	}
	return nil
}

type ListTranslationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationsRequest) Reset() {
	*x = ListTranslationsRequest{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationsRequest) ProtoMessage() {}

func (x *ListTranslationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationsRequest.ProtoReflect.Descriptor instead.
func (*ListTranslationsRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{5}
}

func (x *ListTranslationsRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *ListTranslationsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListTranslationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTranslationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTranslationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  []*Translation         `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationsResponse) Reset() {
	*x = ListTranslationsResponse{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationsResponse) ProtoMessage() {}

func (x *ListTranslationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationsResponse.ProtoReflect.Descriptor instead.
func (*ListTranslationsResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{6}
}

func (x *ListTranslationsResponse) GetTranslations() []*Translation {
	if x != nil {
		return x.Translations
	}
	return nil
}

func (x *ListTranslationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListTranslationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTranslationsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type TranslateSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	SourceLang    string                 `protobuf:"bytes,2,opt,name=source_lang,json=sourceLang,proto3" json:"source_lang,omitempty"`
	TargetLang    string                 `protobuf:"bytes,3,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateSiteRequest) Reset() {
	*x = TranslateSiteRequest{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateSiteRequest) ProtoMessage() {}

func (x *TranslateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateSiteRequest.ProtoReflect.Descriptor instead.
func (*TranslateSiteRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{7}
}

func (x *TranslateSiteRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *TranslateSiteRequest) GetSourceLang() string {
	if x != nil {
		return x.SourceLang
	}
	return ""
}

func (x *TranslateSiteRequest) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

type TranslateSiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  []string               `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateSiteResponse) Reset() {
	*x = TranslateSiteResponse{}
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateSiteResponse) ProtoMessage() {}

func (x *TranslateSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_i18n_v0_i18n_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateSiteResponse.ProtoReflect.Descriptor instead.
func (*TranslateSiteResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_i18n_v0_i18n_proto_rawDescGZIP(), []int{8}
}

func (x *TranslateSiteResponse) GetTranslations() []string {
	if x != nil {
		return x.Translations
	}
	return nil
}

var File_api_protos_i18n_v0_i18n_proto protoreflect.FileDescriptor

const file_api_protos_i18n_v0_i18n_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/protos/i18n/v0/i18n.proto\x12\x04i18n\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\vTranslation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\x05R\bmasterId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\n" +
	"campaignId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12;\n" +
	"\bmetadata\x18\a \x03(\v2\x1f.i18n.Translation.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\x18CreateTranslationRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\x05R\bmasterId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\x05R\n" +
	"campaignId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.i18n.CreateTranslationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x19CreateTranslationResponse\x123\n" +
	"\vtranslation\x18\x01 \x01(\v2\x11.i18n.TranslationR\vtranslation\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\">\n" +
	"\x15GetTranslationRequest\x12%\n" +
	"\x0etranslation_id\x18\x01 \x01(\x05R\rtranslationId\"M\n" +
	"\x16GetTranslationResponse\x123\n" +
	"\vtranslation\x18\x01 \x01(\v2\x11.i18n.TranslationR\vtranslation\"\x87\x01\n" +
	"\x17ListTranslationsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x05R\n" +
	"campaignId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa7\x01\n" +
	"\x18ListTranslationsResponse\x125\n" +
	"\ftranslations\x18\x01 \x03(\v2\x11.i18n.TranslationR\ftranslations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"n\n" +
	"\x14TranslateSiteRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x1f\n" +
	"\vsource_lang\x18\x02 \x01(\tR\n" +
	"sourceLang\x12\x1f\n" +
	"\vtarget_lang\x18\x03 \x01(\tR\n" +
	"targetLang\";\n" +
	"\x15TranslateSiteResponse\x12\"\n" +
	"\ftranslations\x18\x01 \x03(\tR\ftranslations2\xd5\x02\n" +
	"\vI18nService\x12V\n" +
	"\x11CreateTranslation\x12\x1e.i18n.CreateTranslationRequest\x1a\x1f.i18n.CreateTranslationResponse\"\x00\x12M\n" +
	"\x0eGetTranslation\x12\x1b.i18n.GetTranslationRequest\x1a\x1c.i18n.GetTranslationResponse\"\x00\x12S\n" +
	"\x10ListTranslations\x12\x1d.i18n.ListTranslationsRequest\x1a\x1e.i18n.ListTranslationsResponse\"\x00\x12J\n" +
	"\rTranslateSite\x12\x1a.i18n.TranslateSiteRequest\x1a\x1b.i18n.TranslateSiteResponse\"\x00B2Z0github.com/nmxmxh/master-ovasabi/api/protos/i18nb\x06proto3"

var (
	file_api_protos_i18n_v0_i18n_proto_rawDescOnce sync.Once
	file_api_protos_i18n_v0_i18n_proto_rawDescData []byte
)

func file_api_protos_i18n_v0_i18n_proto_rawDescGZIP() []byte {
	file_api_protos_i18n_v0_i18n_proto_rawDescOnce.Do(func() {
		file_api_protos_i18n_v0_i18n_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_i18n_v0_i18n_proto_rawDesc), len(file_api_protos_i18n_v0_i18n_proto_rawDesc)))
	})
	return file_api_protos_i18n_v0_i18n_proto_rawDescData
}

var file_api_protos_i18n_v0_i18n_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_protos_i18n_v0_i18n_proto_goTypes = []any{
	(*Translation)(nil),               // 0: i18n.Translation
	(*CreateTranslationRequest)(nil),  // 1: i18n.CreateTranslationRequest
	(*CreateTranslationResponse)(nil), // 2: i18n.CreateTranslationResponse
	(*GetTranslationRequest)(nil),     // 3: i18n.GetTranslationRequest
	(*GetTranslationResponse)(nil),    // 4: i18n.GetTranslationResponse
	(*ListTranslationsRequest)(nil),   // 5: i18n.ListTranslationsRequest
	(*ListTranslationsResponse)(nil),  // 6: i18n.ListTranslationsResponse
	(*TranslateSiteRequest)(nil),      // 7: i18n.TranslateSiteRequest
	(*TranslateSiteResponse)(nil),     // 8: i18n.TranslateSiteResponse
	nil,                               // 9: i18n.Translation.MetadataEntry
	nil,                               // 10: i18n.CreateTranslationRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_api_protos_i18n_v0_i18n_proto_depIdxs = []int32{
	9,  // 0: i18n.Translation.metadata:type_name -> i18n.Translation.MetadataEntry
	11, // 1: i18n.Translation.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: i18n.CreateTranslationRequest.metadata:type_name -> i18n.CreateTranslationRequest.MetadataEntry
	0,  // 3: i18n.CreateTranslationResponse.translation:type_name -> i18n.Translation
	0,  // 4: i18n.GetTranslationResponse.translation:type_name -> i18n.Translation
	0,  // 5: i18n.ListTranslationsResponse.translations:type_name -> i18n.Translation
	1,  // 6: i18n.I18nService.CreateTranslation:input_type -> i18n.CreateTranslationRequest
	3,  // 7: i18n.I18nService.GetTranslation:input_type -> i18n.GetTranslationRequest
	5,  // 8: i18n.I18nService.ListTranslations:input_type -> i18n.ListTranslationsRequest
	7,  // 9: i18n.I18nService.TranslateSite:input_type -> i18n.TranslateSiteRequest
	2,  // 10: i18n.I18nService.CreateTranslation:output_type -> i18n.CreateTranslationResponse
	4,  // 11: i18n.I18nService.GetTranslation:output_type -> i18n.GetTranslationResponse
	6,  // 12: i18n.I18nService.ListTranslations:output_type -> i18n.ListTranslationsResponse
	8,  // 13: i18n.I18nService.TranslateSite:output_type -> i18n.TranslateSiteResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_protos_i18n_v0_i18n_proto_init() }
func file_api_protos_i18n_v0_i18n_proto_init() {
	if File_api_protos_i18n_v0_i18n_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_i18n_v0_i18n_proto_rawDesc), len(file_api_protos_i18n_v0_i18n_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_i18n_v0_i18n_proto_goTypes,
		DependencyIndexes: file_api_protos_i18n_v0_i18n_proto_depIdxs,
		MessageInfos:      file_api_protos_i18n_v0_i18n_proto_msgTypes,
	}.Build()
	File_api_protos_i18n_v0_i18n_proto = out.File
	file_api_protos_i18n_v0_i18n_proto_goTypes = nil
	file_api_protos_i18n_v0_i18n_proto_depIdxs = nil
}
