version: "2"
run:
  concurrency: 8
  go: ""
  build-tags:
    - integration
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  skip-dirs:
    - amadeus
    - amadeus/backups
    - amadeus/cmd
    - amadeus/pkg
    - amadeus/nexus
    - amadeus/examples
  skip-files:
    - ".*_test.go"
    - ".*\\.pb\\.go"
    - "amadeus/.*\\.go"
linters:
  disable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - gocritic
    - godot
    - gomoddirectives
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
output:
  path-prefix: "" 