// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: api/protos/broadcast/v0/broadcast.proto

package broadcast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Broadcast message for campaigns or services
type Broadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MasterId      int32                  `protobuf:"varint,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"` // e.g., email, sms, push
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,7,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Flexible, JSONB-like
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *Broadcast) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Broadcast) GetMasterId() int32 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *Broadcast) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *Broadcast) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Broadcast) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Broadcast) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Broadcast) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Broadcast) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Broadcast) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type CreateBroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      int32                  `protobuf:"varint,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,6,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBroadcastRequest) Reset() {
	*x = CreateBroadcastRequest{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBroadcastRequest) ProtoMessage() {}

func (x *CreateBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBroadcastRequest.ProtoReflect.Descriptor instead.
func (*CreateBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBroadcastRequest) GetMasterId() int32 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *CreateBroadcastRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CreateBroadcastRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CreateBroadcastRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateBroadcastRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBroadcastRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateBroadcastRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type CreateBroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Broadcast     *Broadcast             `protobuf:"bytes,1,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBroadcastResponse) Reset() {
	*x = CreateBroadcastResponse{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBroadcastResponse) ProtoMessage() {}

func (x *CreateBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBroadcastResponse.ProtoReflect.Descriptor instead.
func (*CreateBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBroadcastResponse) GetBroadcast() *Broadcast {
	if x != nil {
		return x.Broadcast
	}
	return nil
}

func (x *CreateBroadcastResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetBroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BroadcastId   int32                  `protobuf:"varint,1,opt,name=broadcast_id,json=broadcastId,proto3" json:"broadcast_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBroadcastRequest) Reset() {
	*x = GetBroadcastRequest{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBroadcastRequest) ProtoMessage() {}

func (x *GetBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBroadcastRequest.ProtoReflect.Descriptor instead.
func (*GetBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{3}
}

func (x *GetBroadcastRequest) GetBroadcastId() int32 {
	if x != nil {
		return x.BroadcastId
	}
	return 0
}

type GetBroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Broadcast     *Broadcast             `protobuf:"bytes,1,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBroadcastResponse) Reset() {
	*x = GetBroadcastResponse{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBroadcastResponse) ProtoMessage() {}

func (x *GetBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBroadcastResponse.ProtoReflect.Descriptor instead.
func (*GetBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{4}
}

func (x *GetBroadcastResponse) GetBroadcast() *Broadcast {
	if x != nil {
		return x.Broadcast
	}
	return nil
}

type ListBroadcastsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBroadcastsRequest) Reset() {
	*x = ListBroadcastsRequest{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBroadcastsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBroadcastsRequest) ProtoMessage() {}

func (x *ListBroadcastsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBroadcastsRequest.ProtoReflect.Descriptor instead.
func (*ListBroadcastsRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{5}
}

func (x *ListBroadcastsRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *ListBroadcastsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBroadcastsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBroadcastsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Broadcasts    []*Broadcast           `protobuf:"bytes,1,rep,name=broadcasts,proto3" json:"broadcasts,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBroadcastsResponse) Reset() {
	*x = ListBroadcastsResponse{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBroadcastsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBroadcastsResponse) ProtoMessage() {}

func (x *ListBroadcastsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBroadcastsResponse.ProtoReflect.Descriptor instead.
func (*ListBroadcastsResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{6}
}

func (x *ListBroadcastsResponse) GetBroadcasts() []*Broadcast {
	if x != nil {
		return x.Broadcasts
	}
	return nil
}

func (x *ListBroadcastsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListBroadcastsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBroadcastsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// BroadcastActionRequest contains the action to broadcast
type BroadcastActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastActionRequest) Reset() {
	*x = BroadcastActionRequest{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastActionRequest) ProtoMessage() {}

func (x *BroadcastActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastActionRequest.ProtoReflect.Descriptor instead.
func (*BroadcastActionRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{7}
}

func (x *BroadcastActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BroadcastActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *BroadcastActionRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *BroadcastActionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// BroadcastActionResponse contains the broadcast result
type BroadcastActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastActionResponse) Reset() {
	*x = BroadcastActionResponse{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastActionResponse) ProtoMessage() {}

func (x *BroadcastActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastActionResponse.ProtoReflect.Descriptor instead.
func (*BroadcastActionResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{8}
}

func (x *BroadcastActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SubscribeRequest contains subscription parameters
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ActionTypes   []string               `protobuf:"bytes,2,rep,name=action_types,json=actionTypes,proto3" json:"action_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *SubscribeRequest) GetActionTypes() []string {
	if x != nil {
		return x.ActionTypes
	}
	return nil
}

// ActionSummary contains a summary of user actions
type ActionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSummary) Reset() {
	*x = ActionSummary{}
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSummary) ProtoMessage() {}

func (x *ActionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_v0_broadcast_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSummary.ProtoReflect.Descriptor instead.
func (*ActionSummary) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP(), []int{10}
}

func (x *ActionSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActionSummary) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionSummary) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ActionSummary) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ActionSummary) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_protos_broadcast_v0_broadcast_proto protoreflect.FileDescriptor

const file_api_protos_broadcast_v0_broadcast_proto_rawDesc = "" +
	"\n" +
	"'api/protos/broadcast/v0/broadcast.proto\x12\tbroadcast\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x03\n" +
	"\tBroadcast\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\x05R\bmasterId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\n" +
	"campaignId\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12;\n" +
	"\apayload\x18\a \x03(\v2!.broadcast.Broadcast.PayloadEntryR\apayload\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fscheduled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x02\n" +
	"\x16CreateBroadcastRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\x05R\bmasterId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\x05R\n" +
	"campaignId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12H\n" +
	"\apayload\x18\x06 \x03(\v2..broadcast.CreateBroadcastRequest.PayloadEntryR\apayload\x12=\n" +
	"\fscheduled_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x17CreateBroadcastResponse\x122\n" +
	"\tbroadcast\x18\x01 \x01(\v2\x14.broadcast.BroadcastR\tbroadcast\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"8\n" +
	"\x13GetBroadcastRequest\x12!\n" +
	"\fbroadcast_id\x18\x01 \x01(\x05R\vbroadcastId\"J\n" +
	"\x14GetBroadcastResponse\x122\n" +
	"\tbroadcast\x18\x01 \x01(\v2\x14.broadcast.BroadcastR\tbroadcast\"i\n" +
	"\x15ListBroadcastsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x05R\n" +
	"campaignId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x16ListBroadcastsResponse\x124\n" +
	"\n" +
	"broadcasts\x18\x01 \x03(\v2\x14.broadcast.BroadcastR\n" +
	"broadcasts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\x83\x02\n" +
	"\x16BroadcastActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12K\n" +
	"\bmetadata\x18\x04 \x03(\v2/.broadcast.BroadcastActionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x17BroadcastActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\\\n" +
	"\x10SubscribeRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12!\n" +
	"\faction_types\x18\x02 \x03(\tR\vactionTypes\"\x8f\x02\n" +
	"\rActionSummary\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.broadcast.ActionSummary.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc1\x03\n" +
	"\x10BroadcastService\x12Z\n" +
	"\x0fBroadcastAction\x12!.broadcast.BroadcastActionRequest\x1a\".broadcast.BroadcastActionResponse\"\x00\x12O\n" +
	"\x12SubscribeToActions\x12\x1b.broadcast.SubscribeRequest\x1a\x18.broadcast.ActionSummary\"\x000\x01\x12X\n" +
	"\x0fCreateBroadcast\x12!.broadcast.CreateBroadcastRequest\x1a\".broadcast.CreateBroadcastResponse\x12O\n" +
	"\fGetBroadcast\x12\x1e.broadcast.GetBroadcastRequest\x1a\x1f.broadcast.GetBroadcastResponse\x12U\n" +
	"\x0eListBroadcasts\x12 .broadcast.ListBroadcastsRequest\x1a!.broadcast.ListBroadcastsResponseB7Z5github.com/nmxmxh/master-ovasabi/api/protos/broadcastb\x06proto3"

var (
	file_api_protos_broadcast_v0_broadcast_proto_rawDescOnce sync.Once
	file_api_protos_broadcast_v0_broadcast_proto_rawDescData []byte
)

func file_api_protos_broadcast_v0_broadcast_proto_rawDescGZIP() []byte {
	file_api_protos_broadcast_v0_broadcast_proto_rawDescOnce.Do(func() {
		file_api_protos_broadcast_v0_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_broadcast_v0_broadcast_proto_rawDesc), len(file_api_protos_broadcast_v0_broadcast_proto_rawDesc)))
	})
	return file_api_protos_broadcast_v0_broadcast_proto_rawDescData
}

var file_api_protos_broadcast_v0_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_protos_broadcast_v0_broadcast_proto_goTypes = []any{
	(*Broadcast)(nil),               // 0: broadcast.Broadcast
	(*CreateBroadcastRequest)(nil),  // 1: broadcast.CreateBroadcastRequest
	(*CreateBroadcastResponse)(nil), // 2: broadcast.CreateBroadcastResponse
	(*GetBroadcastRequest)(nil),     // 3: broadcast.GetBroadcastRequest
	(*GetBroadcastResponse)(nil),    // 4: broadcast.GetBroadcastResponse
	(*ListBroadcastsRequest)(nil),   // 5: broadcast.ListBroadcastsRequest
	(*ListBroadcastsResponse)(nil),  // 6: broadcast.ListBroadcastsResponse
	(*BroadcastActionRequest)(nil),  // 7: broadcast.BroadcastActionRequest
	(*BroadcastActionResponse)(nil), // 8: broadcast.BroadcastActionResponse
	(*SubscribeRequest)(nil),        // 9: broadcast.SubscribeRequest
	(*ActionSummary)(nil),           // 10: broadcast.ActionSummary
	nil,                             // 11: broadcast.Broadcast.PayloadEntry
	nil,                             // 12: broadcast.CreateBroadcastRequest.PayloadEntry
	nil,                             // 13: broadcast.BroadcastActionRequest.MetadataEntry
	nil,                             // 14: broadcast.ActionSummary.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
}
var file_api_protos_broadcast_v0_broadcast_proto_depIdxs = []int32{
	11, // 0: broadcast.Broadcast.payload:type_name -> broadcast.Broadcast.PayloadEntry
	15, // 1: broadcast.Broadcast.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: broadcast.Broadcast.scheduled_at:type_name -> google.protobuf.Timestamp
	12, // 3: broadcast.CreateBroadcastRequest.payload:type_name -> broadcast.CreateBroadcastRequest.PayloadEntry
	15, // 4: broadcast.CreateBroadcastRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	0,  // 5: broadcast.CreateBroadcastResponse.broadcast:type_name -> broadcast.Broadcast
	0,  // 6: broadcast.GetBroadcastResponse.broadcast:type_name -> broadcast.Broadcast
	0,  // 7: broadcast.ListBroadcastsResponse.broadcasts:type_name -> broadcast.Broadcast
	13, // 8: broadcast.BroadcastActionRequest.metadata:type_name -> broadcast.BroadcastActionRequest.MetadataEntry
	14, // 9: broadcast.ActionSummary.metadata:type_name -> broadcast.ActionSummary.MetadataEntry
	7,  // 10: broadcast.BroadcastService.BroadcastAction:input_type -> broadcast.BroadcastActionRequest
	9,  // 11: broadcast.BroadcastService.SubscribeToActions:input_type -> broadcast.SubscribeRequest
	1,  // 12: broadcast.BroadcastService.CreateBroadcast:input_type -> broadcast.CreateBroadcastRequest
	3,  // 13: broadcast.BroadcastService.GetBroadcast:input_type -> broadcast.GetBroadcastRequest
	5,  // 14: broadcast.BroadcastService.ListBroadcasts:input_type -> broadcast.ListBroadcastsRequest
	8,  // 15: broadcast.BroadcastService.BroadcastAction:output_type -> broadcast.BroadcastActionResponse
	10, // 16: broadcast.BroadcastService.SubscribeToActions:output_type -> broadcast.ActionSummary
	2,  // 17: broadcast.BroadcastService.CreateBroadcast:output_type -> broadcast.CreateBroadcastResponse
	4,  // 18: broadcast.BroadcastService.GetBroadcast:output_type -> broadcast.GetBroadcastResponse
	6,  // 19: broadcast.BroadcastService.ListBroadcasts:output_type -> broadcast.ListBroadcastsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_protos_broadcast_v0_broadcast_proto_init() }
func file_api_protos_broadcast_v0_broadcast_proto_init() {
	if File_api_protos_broadcast_v0_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_broadcast_v0_broadcast_proto_rawDesc), len(file_api_protos_broadcast_v0_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_broadcast_v0_broadcast_proto_goTypes,
		DependencyIndexes: file_api_protos_broadcast_v0_broadcast_proto_depIdxs,
		MessageInfos:      file_api_protos_broadcast_v0_broadcast_proto_msgTypes,
	}.Build()
	File_api_protos_broadcast_v0_broadcast_proto = out.File
	file_api_protos_broadcast_v0_broadcast_proto_goTypes = nil
	file_api_protos_broadcast_v0_broadcast_proto_depIdxs = nil
}
