// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: api/protos/campaign/v0/campaign.proto

package campaign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Campaign struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug           string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RankingFormula string                 `protobuf:"bytes,5,opt,name=ranking_formula,json=rankingFormula,proto3" json:"ranking_formula,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Metadata       string                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_api_protos_campaign_v0_campaign_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Campaign) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Campaign) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetRankingFormula() string {
	if x != nil {
		return x.RankingFormula
	}
	return ""
}

func (x *Campaign) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Campaign) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Campaign) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Campaign) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCampaignRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slug           string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RankingFormula string                 `protobuf:"bytes,4,opt,name=ranking_formula,json=rankingFormula,proto3" json:"ranking_formula,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Metadata       string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_campaign_v0_campaign_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCampaignRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateCampaignRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignRequest) GetRankingFormula() string {
	if x != nil {
		return x.RankingFormula
	}
	return ""
}

func (x *CreateCampaignRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateCampaignRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CreateCampaignRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreateCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse) Reset() {
	*x = CreateCampaignResponse{}
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse) ProtoMessage() {}

func (x *CreateCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_campaign_v0_campaign_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_campaign_v0_campaign_proto_rawDescGZIP(), []int{3}
}

func (x *GetCampaignRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse) Reset() {
	*x = GetCampaignResponse{}
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse) ProtoMessage() {}

func (x *GetCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_campaign_v0_campaign_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_campaign_v0_campaign_proto_rawDescGZIP(), []int{4}
}

func (x *GetCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

var File_api_protos_campaign_v0_campaign_proto protoreflect.FileDescriptor

const file_api_protos_campaign_v0_campaign_proto_rawDesc = "" +
	"\n" +
	"%api/protos/campaign/v0/campaign.proto\x12\bcampaign\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x03\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x0franking_formula\x18\x05 \x01(\tR\x0erankingFormula\x129\n" +
	"\n" +
	"start_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x02\n" +
	"\x15CreateCampaignRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0franking_formula\x18\x04 \x01(\tR\x0erankingFormula\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"H\n" +
	"\x16CreateCampaignResponse\x12.\n" +
	"\bcampaign\x18\x01 \x01(\v2\x12.campaign.CampaignR\bcampaign\"(\n" +
	"\x12GetCampaignRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"E\n" +
	"\x13GetCampaignResponse\x12.\n" +
	"\bcampaign\x18\x01 \x01(\v2\x12.campaign.CampaignR\bcampaign2\xb2\x01\n" +
	"\x0fCampaignService\x12S\n" +
	"\x0eCreateCampaign\x12\x1f.campaign.CreateCampaignRequest\x1a .campaign.CreateCampaignResponse\x12J\n" +
	"\vGetCampaign\x12\x1c.campaign.GetCampaignRequest\x1a\x1d.campaign.GetCampaignResponseB6Z4github.com/nmxmxh/master-ovasabi/api/protos/campaignb\x06proto3"

var (
	file_api_protos_campaign_v0_campaign_proto_rawDescOnce sync.Once
	file_api_protos_campaign_v0_campaign_proto_rawDescData []byte
)

func file_api_protos_campaign_v0_campaign_proto_rawDescGZIP() []byte {
	file_api_protos_campaign_v0_campaign_proto_rawDescOnce.Do(func() {
		file_api_protos_campaign_v0_campaign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_campaign_v0_campaign_proto_rawDesc), len(file_api_protos_campaign_v0_campaign_proto_rawDesc)))
	})
	return file_api_protos_campaign_v0_campaign_proto_rawDescData
}

var file_api_protos_campaign_v0_campaign_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_protos_campaign_v0_campaign_proto_goTypes = []any{
	(*Campaign)(nil),               // 0: campaign.Campaign
	(*CreateCampaignRequest)(nil),  // 1: campaign.CreateCampaignRequest
	(*CreateCampaignResponse)(nil), // 2: campaign.CreateCampaignResponse
	(*GetCampaignRequest)(nil),     // 3: campaign.GetCampaignRequest
	(*GetCampaignResponse)(nil),    // 4: campaign.GetCampaignResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_api_protos_campaign_v0_campaign_proto_depIdxs = []int32{
	5,  // 0: campaign.Campaign.start_date:type_name -> google.protobuf.Timestamp
	5,  // 1: campaign.Campaign.end_date:type_name -> google.protobuf.Timestamp
	5,  // 2: campaign.Campaign.created_at:type_name -> google.protobuf.Timestamp
	5,  // 3: campaign.Campaign.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 4: campaign.CreateCampaignRequest.start_date:type_name -> google.protobuf.Timestamp
	5,  // 5: campaign.CreateCampaignRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 6: campaign.CreateCampaignResponse.campaign:type_name -> campaign.Campaign
	0,  // 7: campaign.GetCampaignResponse.campaign:type_name -> campaign.Campaign
	1,  // 8: campaign.CampaignService.CreateCampaign:input_type -> campaign.CreateCampaignRequest
	3,  // 9: campaign.CampaignService.GetCampaign:input_type -> campaign.GetCampaignRequest
	2,  // 10: campaign.CampaignService.CreateCampaign:output_type -> campaign.CreateCampaignResponse
	4,  // 11: campaign.CampaignService.GetCampaign:output_type -> campaign.GetCampaignResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_protos_campaign_v0_campaign_proto_init() }
func file_api_protos_campaign_v0_campaign_proto_init() {
	if File_api_protos_campaign_v0_campaign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_campaign_v0_campaign_proto_rawDesc), len(file_api_protos_campaign_v0_campaign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_campaign_v0_campaign_proto_goTypes,
		DependencyIndexes: file_api_protos_campaign_v0_campaign_proto_depIdxs,
		MessageInfos:      file_api_protos_campaign_v0_campaign_proto_msgTypes,
	}.Build()
	File_api_protos_campaign_v0_campaign_proto = out.File
	file_api_protos_campaign_v0_campaign_proto_goTypes = nil
	file_api_protos_campaign_v0_campaign_proto_depIdxs = nil
}
