// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: localization/v1/localization.proto

package localizationpb

import (
	v1 "github.com/nmxmxh/master-ovasabi/api/protos/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TranslateRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type TranslateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BatchTranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTranslateRequest) Reset() {
	*x = BatchTranslateRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTranslateRequest) ProtoMessage() {}

func (x *BatchTranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTranslateRequest.ProtoReflect.Descriptor instead.
func (*BatchTranslateRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{2}
}

func (x *BatchTranslateRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchTranslateRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type BatchTranslateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *v1.Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTranslateResponse) Reset() {
	*x = BatchTranslateResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTranslateResponse) ProtoMessage() {}

func (x *BatchTranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTranslateResponse.ProtoReflect.Descriptor instead.
func (*BatchTranslateResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{3}
}

func (x *BatchTranslateResponse) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *BatchTranslateResponse) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateTranslationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      *v1.Metadata           `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CampaignId    int64                  `protobuf:"varint,5,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranslationRequest) Reset() {
	*x = CreateTranslationRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranslationRequest) ProtoMessage() {}

func (x *CreateTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranslationRequest.ProtoReflect.Descriptor instead.
func (*CreateTranslationRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTranslationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateTranslationRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateTranslationRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateTranslationRequest) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateTranslationRequest) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type CreateTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   *Translation           `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranslationResponse) Reset() {
	*x = CreateTranslationResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranslationResponse) ProtoMessage() {}

func (x *CreateTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranslationResponse.ProtoReflect.Descriptor instead.
func (*CreateTranslationResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTranslationResponse) GetTranslation() *Translation {
	if x != nil {
		return x.Translation
	}
	return nil
}

func (x *CreateTranslationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTranslationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TranslationId string                 `protobuf:"bytes,1,opt,name=translation_id,json=translationId,proto3" json:"translation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationRequest) Reset() {
	*x = GetTranslationRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationRequest) ProtoMessage() {}

func (x *GetTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationRequest.ProtoReflect.Descriptor instead.
func (*GetTranslationRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{6}
}

func (x *GetTranslationRequest) GetTranslationId() string {
	if x != nil {
		return x.TranslationId
	}
	return ""
}

type GetTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   *Translation           `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationResponse) Reset() {
	*x = GetTranslationResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationResponse) ProtoMessage() {}

func (x *GetTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationResponse.ProtoReflect.Descriptor instead.
func (*GetTranslationResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{7}
}

func (x *GetTranslationResponse) GetTranslation() *Translation {
	if x != nil {
		return x.Translation
	}
	return nil
}

type ListTranslationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CampaignId    int64                  `protobuf:"varint,4,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationsRequest) Reset() {
	*x = ListTranslationsRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationsRequest) ProtoMessage() {}

func (x *ListTranslationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationsRequest.ProtoReflect.Descriptor instead.
func (*ListTranslationsRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{8}
}

func (x *ListTranslationsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListTranslationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTranslationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTranslationsRequest) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type ListTranslationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  []*Translation         `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationsResponse) Reset() {
	*x = ListTranslationsResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationsResponse) ProtoMessage() {}

func (x *ListTranslationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationsResponse.ProtoReflect.Descriptor instead.
func (*ListTranslationsResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{9}
}

func (x *ListTranslationsResponse) GetTranslations() []*Translation {
	if x != nil {
		return x.Translations
	}
	return nil
}

func (x *ListTranslationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListTranslationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTranslationsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type Translation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      *v1.Metadata           `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CampaignId    int64                  `protobuf:"varint,7,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Translation) Reset() {
	*x = Translation{}
	mi := &file_localization_v1_localization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Translation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation) ProtoMessage() {}

func (x *Translation) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation.ProtoReflect.Descriptor instead.
func (*Translation) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{10}
}

func (x *Translation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Translation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Translation) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Translation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Translation) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Translation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Translation) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type GetPricingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPricingRuleRequest) Reset() {
	*x = GetPricingRuleRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPricingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPricingRuleRequest) ProtoMessage() {}

func (x *GetPricingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPricingRuleRequest.ProtoReflect.Descriptor instead.
func (*GetPricingRuleRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{11}
}

func (x *GetPricingRuleRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetPricingRuleRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetPricingRuleRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetPricingRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PricingRule           `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPricingRuleResponse) Reset() {
	*x = GetPricingRuleResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPricingRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPricingRuleResponse) ProtoMessage() {}

func (x *GetPricingRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPricingRuleResponse.ProtoReflect.Descriptor instead.
func (*GetPricingRuleResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{12}
}

func (x *GetPricingRuleResponse) GetRule() *PricingRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type SetPricingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PricingRule           `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPricingRuleRequest) Reset() {
	*x = SetPricingRuleRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPricingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPricingRuleRequest) ProtoMessage() {}

func (x *SetPricingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPricingRuleRequest.ProtoReflect.Descriptor instead.
func (*SetPricingRuleRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{13}
}

func (x *SetPricingRuleRequest) GetRule() *PricingRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type SetPricingRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPricingRuleResponse) Reset() {
	*x = SetPricingRuleResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPricingRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPricingRuleResponse) ProtoMessage() {}

func (x *SetPricingRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPricingRuleResponse.ProtoReflect.Descriptor instead.
func (*SetPricingRuleResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{14}
}

func (x *SetPricingRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPricingRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPricingRulesRequest) Reset() {
	*x = ListPricingRulesRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPricingRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPricingRulesRequest) ProtoMessage() {}

func (x *ListPricingRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPricingRulesRequest.ProtoReflect.Descriptor instead.
func (*ListPricingRulesRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{15}
}

func (x *ListPricingRulesRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *ListPricingRulesRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListPricingRulesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPricingRulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPricingRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PricingRule         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPricingRulesResponse) Reset() {
	*x = ListPricingRulesResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPricingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPricingRulesResponse) ProtoMessage() {}

func (x *ListPricingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPricingRulesResponse.ProtoReflect.Descriptor instead.
func (*ListPricingRulesResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{16}
}

func (x *ListPricingRulesResponse) GetRules() []*PricingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ListPricingRulesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPricingRulesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPricingRulesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type PricingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	AffluenceTier string                 `protobuf:"bytes,6,opt,name=affluence_tier,json=affluenceTier,proto3" json:"affluence_tier,omitempty"`
	DemandLevel   string                 `protobuf:"bytes,7,opt,name=demand_level,json=demandLevel,proto3" json:"demand_level,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,8,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,9,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectiveFrom *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	EffectiveTo   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=effective_to,json=effectiveTo,proto3" json:"effective_to,omitempty"`
	Notes         string                 `protobuf:"bytes,12,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingRule) Reset() {
	*x = PricingRule{}
	mi := &file_localization_v1_localization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRule) ProtoMessage() {}

func (x *PricingRule) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRule.ProtoReflect.Descriptor instead.
func (*PricingRule) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{17}
}

func (x *PricingRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PricingRule) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PricingRule) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PricingRule) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PricingRule) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *PricingRule) GetAffluenceTier() string {
	if x != nil {
		return x.AffluenceTier
	}
	return ""
}

func (x *PricingRule) GetDemandLevel() string {
	if x != nil {
		return x.DemandLevel
	}
	return ""
}

func (x *PricingRule) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *PricingRule) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *PricingRule) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

func (x *PricingRule) GetEffectiveTo() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveTo
	}
	return nil
}

func (x *PricingRule) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *PricingRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PricingRule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListLocalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalesRequest) Reset() {
	*x = ListLocalesRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalesRequest) ProtoMessage() {}

func (x *ListLocalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalesRequest.ProtoReflect.Descriptor instead.
func (*ListLocalesRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{18}
}

type ListLocalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locales       []*Locale              `protobuf:"bytes,1,rep,name=locales,proto3" json:"locales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalesResponse) Reset() {
	*x = ListLocalesResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalesResponse) ProtoMessage() {}

func (x *ListLocalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalesResponse.ProtoReflect.Descriptor instead.
func (*ListLocalesResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{19}
}

func (x *ListLocalesResponse) GetLocales() []*Locale {
	if x != nil {
		return x.Locales
	}
	return nil
}

type GetLocaleMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocaleMetadataRequest) Reset() {
	*x = GetLocaleMetadataRequest{}
	mi := &file_localization_v1_localization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocaleMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocaleMetadataRequest) ProtoMessage() {}

func (x *GetLocaleMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocaleMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetLocaleMetadataRequest) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{20}
}

func (x *GetLocaleMetadataRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type GetLocaleMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        *Locale                `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocaleMetadataResponse) Reset() {
	*x = GetLocaleMetadataResponse{}
	mi := &file_localization_v1_localization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocaleMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocaleMetadataResponse) ProtoMessage() {}

func (x *GetLocaleMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocaleMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetLocaleMetadataResponse) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{21}
}

func (x *GetLocaleMetadataResponse) GetLocale() *Locale {
	if x != nil {
		return x.Locale
	}
	return nil
}

type Locale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Regions       []string               `protobuf:"bytes,5,rep,name=regions,proto3" json:"regions,omitempty"`
	Metadata      *v1.Metadata           `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locale) Reset() {
	*x = Locale{}
	mi := &file_localization_v1_localization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{22}
}

func (x *Locale) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Locale) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Locale) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Locale) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Locale) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *Locale) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Localization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      *v1.Metadata           `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CampaignId    int64                  `protobuf:"varint,7,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Localization) Reset() {
	*x = Localization{}
	mi := &file_localization_v1_localization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Localization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Localization) ProtoMessage() {}

func (x *Localization) ProtoReflect() protoreflect.Message {
	mi := &file_localization_v1_localization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Localization.ProtoReflect.Descriptor instead.
func (*Localization) Descriptor() ([]byte, []int) {
	return file_localization_v1_localization_proto_rawDescGZIP(), []int{23}
}

func (x *Localization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Localization) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Localization) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Localization) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Localization) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Localization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Localization) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

var File_localization_v1_localization_proto protoreflect.FileDescriptor

const file_localization_v1_localization_proto_rawDesc = "" +
	"\n" +
	"\"localization/v1/localization.proto\x12\x0flocalization.v1\x1a\x18common/v1/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x10TranslateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\")\n" +
	"\x11TranslateResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"C\n" +
	"\x15BatchTranslateRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"\xce\x01\n" +
	"\x16BatchTranslateResponse\x12K\n" +
	"\x06values\x18\x01 \x03(\v23.localization.v1.BatchTranslateResponse.ValuesEntryR\x06values\x12,\n" +
	"\bmetadata\x18\x02 \x01(\v2\x10.common.MetadataR\bmetadata\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x18CreateTranslationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12,\n" +
	"\bmetadata\x18\x04 \x01(\v2\x10.common.MetadataR\bmetadata\x12\x1f\n" +
	"\vcampaign_id\x18\x05 \x01(\x03R\n" +
	"campaignId\"u\n" +
	"\x19CreateTranslationResponse\x12>\n" +
	"\vtranslation\x18\x01 \x01(\v2\x1c.localization.v1.TranslationR\vtranslation\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\">\n" +
	"\x15GetTranslationRequest\x12%\n" +
	"\x0etranslation_id\x18\x01 \x01(\tR\rtranslationId\"X\n" +
	"\x16GetTranslationResponse\x12>\n" +
	"\vtranslation\x18\x01 \x01(\v2\x1c.localization.v1.TranslationR\vtranslation\"\x87\x01\n" +
	"\x17ListTranslationsRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vcampaign_id\x18\x04 \x01(\x03R\n" +
	"campaignId\"\xb2\x01\n" +
	"\x18ListTranslationsResponse\x12@\n" +
	"\ftranslations\x18\x01 \x03(\v2\x1c.localization.v1.TranslationR\ftranslations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xeb\x01\n" +
	"\vTranslation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12,\n" +
	"\bmetadata\x18\x05 \x01(\v2\x10.common.MetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vcampaign_id\x18\a \x01(\x03R\n" +
	"campaignId\"f\n" +
	"\x15GetPricingRuleRequest\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\"J\n" +
	"\x16GetPricingRuleResponse\x120\n" +
	"\x04rule\x18\x01 \x01(\v2\x1c.localization.v1.PricingRuleR\x04rule\"I\n" +
	"\x15SetPricingRuleRequest\x120\n" +
	"\x04rule\x18\x01 \x01(\v2\x1c.localization.v1.PricingRuleR\x04rule\"2\n" +
	"\x16SetPricingRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x85\x01\n" +
	"\x17ListPricingRulesRequest\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x18ListPricingRulesResponse\x122\n" +
	"\x05rules\x18\x01 \x03(\v2\x1c.localization.v1.PricingRuleR\x05rules\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xa8\x04\n" +
	"\vPricingRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\x12%\n" +
	"\x0eaffluence_tier\x18\x06 \x01(\tR\raffluenceTier\x12!\n" +
	"\fdemand_level\x18\a \x01(\tR\vdemandLevel\x12\x1e\n" +
	"\n" +
	"multiplier\x18\b \x01(\x01R\n" +
	"multiplier\x12\x1d\n" +
	"\n" +
	"base_price\x18\t \x01(\x01R\tbasePrice\x12A\n" +
	"\x0eeffective_from\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveFrom\x12=\n" +
	"\feffective_to\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\veffectiveTo\x12\x14\n" +
	"\x05notes\x18\f \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x14\n" +
	"\x12ListLocalesRequest\"H\n" +
	"\x13ListLocalesResponse\x121\n" +
	"\alocales\x18\x01 \x03(\v2\x17.localization.v1.LocaleR\alocales\"2\n" +
	"\x18GetLocaleMetadataRequest\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\"L\n" +
	"\x19GetLocaleMetadataResponse\x12/\n" +
	"\x06locale\x18\x01 \x01(\v2\x17.localization.v1.LocaleR\x06locale\"\xb6\x01\n" +
	"\x06Locale\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\aregions\x18\x05 \x03(\tR\aregions\x12,\n" +
	"\bmetadata\x18\x06 \x01(\v2\x10.common.MetadataR\bmetadata\"\xec\x01\n" +
	"\fLocalization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12,\n" +
	"\bmetadata\x18\x05 \x01(\v2\x10.common.MetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vcampaign_id\x18\a \x01(\x03R\n" +
	"campaignId2\xf9\a\n" +
	"\x13LocalizationService\x12R\n" +
	"\tTranslate\x12!.localization.v1.TranslateRequest\x1a\".localization.v1.TranslateResponse\x12a\n" +
	"\x0eBatchTranslate\x12&.localization.v1.BatchTranslateRequest\x1a'.localization.v1.BatchTranslateResponse\x12j\n" +
	"\x11CreateTranslation\x12).localization.v1.CreateTranslationRequest\x1a*.localization.v1.CreateTranslationResponse\x12a\n" +
	"\x0eGetTranslation\x12&.localization.v1.GetTranslationRequest\x1a'.localization.v1.GetTranslationResponse\x12g\n" +
	"\x10ListTranslations\x12(.localization.v1.ListTranslationsRequest\x1a).localization.v1.ListTranslationsResponse\x12a\n" +
	"\x0eGetPricingRule\x12&.localization.v1.GetPricingRuleRequest\x1a'.localization.v1.GetPricingRuleResponse\x12a\n" +
	"\x0eSetPricingRule\x12&.localization.v1.SetPricingRuleRequest\x1a'.localization.v1.SetPricingRuleResponse\x12g\n" +
	"\x10ListPricingRules\x12(.localization.v1.ListPricingRulesRequest\x1a).localization.v1.ListPricingRulesResponse\x12X\n" +
	"\vListLocales\x12#.localization.v1.ListLocalesRequest\x1a$.localization.v1.ListLocalesResponse\x12j\n" +
	"\x11GetLocaleMetadata\x12).localization.v1.GetLocaleMetadataRequest\x1a*.localization.v1.GetLocaleMetadataResponseBLZJgithub.com/nmxmxh/master-ovasabi/api/protos/localization/v1;localizationpbb\x06proto3"

var (
	file_localization_v1_localization_proto_rawDescOnce sync.Once
	file_localization_v1_localization_proto_rawDescData []byte
)

func file_localization_v1_localization_proto_rawDescGZIP() []byte {
	file_localization_v1_localization_proto_rawDescOnce.Do(func() {
		file_localization_v1_localization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localization_v1_localization_proto_rawDesc), len(file_localization_v1_localization_proto_rawDesc)))
	})
	return file_localization_v1_localization_proto_rawDescData
}

var file_localization_v1_localization_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_localization_v1_localization_proto_goTypes = []any{
	(*TranslateRequest)(nil),          // 0: localization.v1.TranslateRequest
	(*TranslateResponse)(nil),         // 1: localization.v1.TranslateResponse
	(*BatchTranslateRequest)(nil),     // 2: localization.v1.BatchTranslateRequest
	(*BatchTranslateResponse)(nil),    // 3: localization.v1.BatchTranslateResponse
	(*CreateTranslationRequest)(nil),  // 4: localization.v1.CreateTranslationRequest
	(*CreateTranslationResponse)(nil), // 5: localization.v1.CreateTranslationResponse
	(*GetTranslationRequest)(nil),     // 6: localization.v1.GetTranslationRequest
	(*GetTranslationResponse)(nil),    // 7: localization.v1.GetTranslationResponse
	(*ListTranslationsRequest)(nil),   // 8: localization.v1.ListTranslationsRequest
	(*ListTranslationsResponse)(nil),  // 9: localization.v1.ListTranslationsResponse
	(*Translation)(nil),               // 10: localization.v1.Translation
	(*GetPricingRuleRequest)(nil),     // 11: localization.v1.GetPricingRuleRequest
	(*GetPricingRuleResponse)(nil),    // 12: localization.v1.GetPricingRuleResponse
	(*SetPricingRuleRequest)(nil),     // 13: localization.v1.SetPricingRuleRequest
	(*SetPricingRuleResponse)(nil),    // 14: localization.v1.SetPricingRuleResponse
	(*ListPricingRulesRequest)(nil),   // 15: localization.v1.ListPricingRulesRequest
	(*ListPricingRulesResponse)(nil),  // 16: localization.v1.ListPricingRulesResponse
	(*PricingRule)(nil),               // 17: localization.v1.PricingRule
	(*ListLocalesRequest)(nil),        // 18: localization.v1.ListLocalesRequest
	(*ListLocalesResponse)(nil),       // 19: localization.v1.ListLocalesResponse
	(*GetLocaleMetadataRequest)(nil),  // 20: localization.v1.GetLocaleMetadataRequest
	(*GetLocaleMetadataResponse)(nil), // 21: localization.v1.GetLocaleMetadataResponse
	(*Locale)(nil),                    // 22: localization.v1.Locale
	(*Localization)(nil),              // 23: localization.v1.Localization
	nil,                               // 24: localization.v1.BatchTranslateResponse.ValuesEntry
	(*v1.Metadata)(nil),               // 25: common.Metadata
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
}
var file_localization_v1_localization_proto_depIdxs = []int32{
	24, // 0: localization.v1.BatchTranslateResponse.values:type_name -> localization.v1.BatchTranslateResponse.ValuesEntry
	25, // 1: localization.v1.BatchTranslateResponse.metadata:type_name -> common.Metadata
	25, // 2: localization.v1.CreateTranslationRequest.metadata:type_name -> common.Metadata
	10, // 3: localization.v1.CreateTranslationResponse.translation:type_name -> localization.v1.Translation
	10, // 4: localization.v1.GetTranslationResponse.translation:type_name -> localization.v1.Translation
	10, // 5: localization.v1.ListTranslationsResponse.translations:type_name -> localization.v1.Translation
	25, // 6: localization.v1.Translation.metadata:type_name -> common.Metadata
	26, // 7: localization.v1.Translation.created_at:type_name -> google.protobuf.Timestamp
	17, // 8: localization.v1.GetPricingRuleResponse.rule:type_name -> localization.v1.PricingRule
	17, // 9: localization.v1.SetPricingRuleRequest.rule:type_name -> localization.v1.PricingRule
	17, // 10: localization.v1.ListPricingRulesResponse.rules:type_name -> localization.v1.PricingRule
	26, // 11: localization.v1.PricingRule.effective_from:type_name -> google.protobuf.Timestamp
	26, // 12: localization.v1.PricingRule.effective_to:type_name -> google.protobuf.Timestamp
	26, // 13: localization.v1.PricingRule.created_at:type_name -> google.protobuf.Timestamp
	26, // 14: localization.v1.PricingRule.updated_at:type_name -> google.protobuf.Timestamp
	22, // 15: localization.v1.ListLocalesResponse.locales:type_name -> localization.v1.Locale
	22, // 16: localization.v1.GetLocaleMetadataResponse.locale:type_name -> localization.v1.Locale
	25, // 17: localization.v1.Locale.metadata:type_name -> common.Metadata
	25, // 18: localization.v1.Localization.metadata:type_name -> common.Metadata
	26, // 19: localization.v1.Localization.created_at:type_name -> google.protobuf.Timestamp
	0,  // 20: localization.v1.LocalizationService.Translate:input_type -> localization.v1.TranslateRequest
	2,  // 21: localization.v1.LocalizationService.BatchTranslate:input_type -> localization.v1.BatchTranslateRequest
	4,  // 22: localization.v1.LocalizationService.CreateTranslation:input_type -> localization.v1.CreateTranslationRequest
	6,  // 23: localization.v1.LocalizationService.GetTranslation:input_type -> localization.v1.GetTranslationRequest
	8,  // 24: localization.v1.LocalizationService.ListTranslations:input_type -> localization.v1.ListTranslationsRequest
	11, // 25: localization.v1.LocalizationService.GetPricingRule:input_type -> localization.v1.GetPricingRuleRequest
	13, // 26: localization.v1.LocalizationService.SetPricingRule:input_type -> localization.v1.SetPricingRuleRequest
	15, // 27: localization.v1.LocalizationService.ListPricingRules:input_type -> localization.v1.ListPricingRulesRequest
	18, // 28: localization.v1.LocalizationService.ListLocales:input_type -> localization.v1.ListLocalesRequest
	20, // 29: localization.v1.LocalizationService.GetLocaleMetadata:input_type -> localization.v1.GetLocaleMetadataRequest
	1,  // 30: localization.v1.LocalizationService.Translate:output_type -> localization.v1.TranslateResponse
	3,  // 31: localization.v1.LocalizationService.BatchTranslate:output_type -> localization.v1.BatchTranslateResponse
	5,  // 32: localization.v1.LocalizationService.CreateTranslation:output_type -> localization.v1.CreateTranslationResponse
	7,  // 33: localization.v1.LocalizationService.GetTranslation:output_type -> localization.v1.GetTranslationResponse
	9,  // 34: localization.v1.LocalizationService.ListTranslations:output_type -> localization.v1.ListTranslationsResponse
	12, // 35: localization.v1.LocalizationService.GetPricingRule:output_type -> localization.v1.GetPricingRuleResponse
	14, // 36: localization.v1.LocalizationService.SetPricingRule:output_type -> localization.v1.SetPricingRuleResponse
	16, // 37: localization.v1.LocalizationService.ListPricingRules:output_type -> localization.v1.ListPricingRulesResponse
	19, // 38: localization.v1.LocalizationService.ListLocales:output_type -> localization.v1.ListLocalesResponse
	21, // 39: localization.v1.LocalizationService.GetLocaleMetadata:output_type -> localization.v1.GetLocaleMetadataResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_localization_v1_localization_proto_init() }
func file_localization_v1_localization_proto_init() {
	if File_localization_v1_localization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localization_v1_localization_proto_rawDesc), len(file_localization_v1_localization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_localization_v1_localization_proto_goTypes,
		DependencyIndexes: file_localization_v1_localization_proto_depIdxs,
		MessageInfos:      file_localization_v1_localization_proto_msgTypes,
	}.Build()
	File_localization_v1_localization_proto = out.File
	file_localization_v1_localization_proto_goTypes = nil
	file_localization_v1_localization_proto_depIdxs = nil
}
