# ----------- Build Stage -----------
FROM golang:1.24-alpine AS builder

WORKDIR /nexus

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .

# Build the Nexus binary
RUN --mount=type=cache,target=/go/pkg/mod CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /nexus/nexus ./cmd/nexus

# ----------- Final Stage (Distroless) -----------
FROM gcr.io/distroless/base-debian11

WORKDIR /nexus

COPY --from=builder /nexus/nexus .

USER nonroot:nonroot

EXPOSE 50052 9090

ENTRYPOINT ["/nexus/nexus"]