version: '3.8'
services:
  wasm-frontend:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.wasm
      target: prod
    ports:
      - '8080:80'
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - ovasabi-network

networks:
  ovasabi-network:
    external: true
