# Dockerfile for ws-gateway (central WebSocket gateway)
FROM golang:1.24-alpine AS builder
WORKDIR /ws
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod go build -o ws-gateway ./internal/server/ws-gateway

FROM alpine:3.19
WORKDIR /ws
COPY --from=builder /ws/ws-gateway /ws/ws-gateway
CMD ["/ws/ws-gateway"]
