version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"   # Jaeger thrift compact protocol
      - "6832:6832/udp"   # Jaeger thrift binary protocol
      - "5778:5778"       # Jaeger admin port
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - ovasabi-network

networks:
  ovasabi-network:
    driver: bridge 