version: '3.8'
services:
  wasm-frontend:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.wasm
      target: prod
    ports:
      - '8088:80'
    restart: unless-stopped
    networks:
      - ovasabi-network

networks:
  ovasabi-network:
