name: master-ovasabi

services:
  app:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - ovasabi/master-ovasabi:latest
    environment:
      APP_ENV: '${APP_ENV:-development}'
      APP_NAME: '${APP_NAME:-master-ovasabi}'
      ENVIRONMENT: development
      LOG_LEVEL: debug
      CONFIG_PATH: /app/config/config.yaml
      DB_HOST: postgres
      DB_PORT: '${DB_PORT:-5432}'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'master_ovasabi'
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
      ADMIN_USER: 'nmxmxh'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      NEXUS_GRPC_ADDR: 'nexus:50052'
      HTTP_PORT: '8080'
      METRICS_PORT: ':9090'
    volumes:
      - ./config:/app/config:ro
      - ./amadeus/knowledge_graph.json:/app/amadeus/knowledge_graph.json
      - ./amadeus/backups:/app/amadeus/backups
      # Proto codegen for Go is now in-place; no need to mount gen/go
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'grpc_health_probe', '-addr=localhost:8080']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - ovasabi-network
    env_file:
      - ../../.env
    ports:
      - '8080:8080'

  wasm-frontend:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.wasm
      target: prod
    networks:
      - ovasabi-network
    depends_on:
      - app
    restart: unless-stopped

  redis:
    image: redis:8
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    volumes:
      - ../../redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    command:
      ['redis-server', '/usr/local/etc/redis/redis.conf', '--requirepass', '${REDIS_PASSWORD}']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ovasabi-network

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-master_ovasabi}'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'master_ovasabi'
      ADMIN_USER: 'nmxmxh'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'listen_addresses=*', '-c', 'max_connections=100']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ovasabi-network
    env_file:
      - ../../.env

  migrate:
    image: migrate/migrate
    volumes:
      - ../../database/migrations:/migrations
    networks:
      - ovasabi-network
    env_file:
      - ../../.env
    environment:
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'master_ovasabi'
      ADMIN_USER: 'nmxmxh'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'

  postgres-init:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-master_ovasabi}'
      DB_USER: '${DB_USER:-postgres}'
      DB_PASSWORD: '${DB_PASSWORD:-postgres}'
      DB_NAME: '${DB_NAME:-master_ovasabi}'
      ADMIN_USER: '${ADMIN_USER:-nmxmxh}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
    entrypoint:
      [
        '/bin/sh',
        '-c',
        "export PGPASSWORD='$DB_PASSWORD'; until pg_isready -h postgres -U '$DB_USER'; do echo
        'Waiting for postgres...'; sleep 2; done && psql -h postgres -U '$DB_USER' -d '$DB_NAME' -c
        'CREATE ROLE \"$ADMIN_USER\" WITH LOGIN PASSWORD '\\''$ADMIN_PASSWORD'\\'' SUPERUSER;' ||
        true"
      ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ovasabi-network
    env_file:
      - ../../.env

  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - '5002:5000'
    restart: unless-stopped

  nexus:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.nexus
    ports:
      - '50052:50052'
      - '9090:9090'
    environment:
      APP_ENV: '${APP_ENV:-development}'
      LOG_LEVEL: info
      SERVICE_NAME: nexus
      NEXUS_GRPC_ADDR: ':50052'
      METRICS_PORT: ':9090'
      REDIS_PASSWORD: '${REDIS_PASSWORD:-@Osiano1995}'
    networks:
      - ovasabi-network
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  media-streaming:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.media-streaming
    ports:
      - '8081:8081'
    environment:
      APP_ENV: '${APP_ENV:-development}'
      LOG_LEVEL: debug
      SERVICE_NAME: media-streaming
      NEXUS_GRPC_ADDR: 'nexus:50052'
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
      DB_HOST: postgres
      DB_PORT: '${DB_PORT:-5432}'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'master_ovasabi'
      CAMPAIGN_ID: '${CAMPAIGN_ID:-0}'
    depends_on:
      nexus:
        condition: service_started
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - ovasabi-network
    restart: unless-stopped
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.25
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/public:/usr/share/nginx/html:ro
      # - ./deployments/docker/certs:/etc/nginx/certs:ro  # Uncomment and set path if using SSL certs
    depends_on:
      - app
      - wasm-frontend
    networks:
      - ovasabi-network
    restart: unless-stopped

  ws-gateway:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.ws-gateway
    ports:
      - '8090:8090'
    environment:
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
      LOG_LEVEL: debug
    depends_on:
      - redis
    networks:
      - ovasabi-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  ovasabi-network:
    external: true
