server:
  host: "0.0.0.0"
  port: 80
  debug: false

database:
  host: "${DB_HOST}"
  port: 5432
  name: "ovasabi_prod"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"

logging:
  level: "info"
  format: "json"

auth:
  jwt_secret: "${JWT_SECRET}"
  token_expiry: "12h"

api:
  rate_limit: 100
  timeout: "10s"

feature_flags:
  enable_new_features: false
  maintenance_mode: false 