server:
  host: 'localhost'
  port: 8081
  debug: true

database:
  host: '${DB_HOST:-postgres}'
  port: ${DB_PORT:-5432}
  name: '${DB_NAME:-ovasabi_test}'
  user: '${DB_USER:-test_user}'
  password: '${DB_PASSWORD:-test_password}'

logging:
  level: 'debug'
  format: 'console'

auth:
  jwt_secret: '${JWT_SECRET:-test_secret_key}'
  token_expiry: '1h'

api:
  rate_limit: 0 # Disabled for testing
  timeout: '5s'

feature_flags:
  enable_new_features: true
  maintenance_mode: false

redis:
  host: '${REDIS_HOST:-redis}'
  port: ${REDIS_PORT:-6379}
  password: '${REDIS_PASSWORD:-test_password}'
