# Default values for ovasabi Helm chart

image:
  repository: ovasabi/master-ovasabi
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

wasmFrontend:
  replicaCount: 2
  image:
    repository: wasm-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8100

nexus:
  replicaCount: 2
  image:
    repository: nexus
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9000

redis:
  image:
    repository: redis
    tag: 7.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379

postgres:
  image:
    repository: postgres
    tag: 15
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  dbPassword: "supersecure"

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

platformMetadata: "system_version=2.0.0,orchestration=enabled"
featureFlags: "search,ai,orchestration"
ingress:
  host: "yourdomain.com" 