// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: api/protos/broadcast/broadcast.proto

package broadcast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BroadcastActionRequest contains the action to broadcast
type BroadcastActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastActionRequest) Reset() {
	*x = BroadcastActionRequest{}
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastActionRequest) ProtoMessage() {}

func (x *BroadcastActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastActionRequest.ProtoReflect.Descriptor instead.
func (*BroadcastActionRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BroadcastActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *BroadcastActionRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *BroadcastActionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// BroadcastActionResponse contains the broadcast result
type BroadcastActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastActionResponse) Reset() {
	*x = BroadcastActionResponse{}
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastActionResponse) ProtoMessage() {}

func (x *BroadcastActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastActionResponse.ProtoReflect.Descriptor instead.
func (*BroadcastActionResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SubscribeRequest contains subscription parameters
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ActionTypes   []string               `protobuf:"bytes,2,rep,name=action_types,json=actionTypes,proto3" json:"action_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_broadcast_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *SubscribeRequest) GetActionTypes() []string {
	if x != nil {
		return x.ActionTypes
	}
	return nil
}

// ActionSummary contains a summary of user actions
type ActionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSummary) Reset() {
	*x = ActionSummary{}
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSummary) ProtoMessage() {}

func (x *ActionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_broadcast_broadcast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSummary.ProtoReflect.Descriptor instead.
func (*ActionSummary) Descriptor() ([]byte, []int) {
	return file_api_protos_broadcast_broadcast_proto_rawDescGZIP(), []int{3}
}

func (x *ActionSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActionSummary) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionSummary) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ActionSummary) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ActionSummary) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_protos_broadcast_broadcast_proto protoreflect.FileDescriptor

const file_api_protos_broadcast_broadcast_proto_rawDesc = "" +
	"\n" +
	"$api/protos/broadcast/broadcast.proto\x12\tbroadcast\"\x83\x02\n" +
	"\x16BroadcastActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12K\n" +
	"\bmetadata\x18\x04 \x03(\v2/.broadcast.BroadcastActionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x17BroadcastActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\\\n" +
	"\x10SubscribeRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12!\n" +
	"\faction_types\x18\x02 \x03(\tR\vactionTypes\"\x8f\x02\n" +
	"\rActionSummary\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.broadcast.ActionSummary.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbf\x01\n" +
	"\x10BroadcastService\x12Z\n" +
	"\x0fBroadcastAction\x12!.broadcast.BroadcastActionRequest\x1a\".broadcast.BroadcastActionResponse\"\x00\x12O\n" +
	"\x12SubscribeToActions\x12\x1b.broadcast.SubscribeRequest\x1a\x18.broadcast.ActionSummary\"\x000\x01B7Z5github.com/nmxmxh/master-ovasabi/api/protos/broadcastb\x06proto3"

var (
	file_api_protos_broadcast_broadcast_proto_rawDescOnce sync.Once
	file_api_protos_broadcast_broadcast_proto_rawDescData []byte
)

func file_api_protos_broadcast_broadcast_proto_rawDescGZIP() []byte {
	file_api_protos_broadcast_broadcast_proto_rawDescOnce.Do(func() {
		file_api_protos_broadcast_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_broadcast_broadcast_proto_rawDesc), len(file_api_protos_broadcast_broadcast_proto_rawDesc)))
	})
	return file_api_protos_broadcast_broadcast_proto_rawDescData
}

var file_api_protos_broadcast_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_protos_broadcast_broadcast_proto_goTypes = []any{
	(*BroadcastActionRequest)(nil),  // 0: broadcast.BroadcastActionRequest
	(*BroadcastActionResponse)(nil), // 1: broadcast.BroadcastActionResponse
	(*SubscribeRequest)(nil),        // 2: broadcast.SubscribeRequest
	(*ActionSummary)(nil),           // 3: broadcast.ActionSummary
	nil,                             // 4: broadcast.BroadcastActionRequest.MetadataEntry
	nil,                             // 5: broadcast.ActionSummary.MetadataEntry
}
var file_api_protos_broadcast_broadcast_proto_depIdxs = []int32{
	4, // 0: broadcast.BroadcastActionRequest.metadata:type_name -> broadcast.BroadcastActionRequest.MetadataEntry
	5, // 1: broadcast.ActionSummary.metadata:type_name -> broadcast.ActionSummary.MetadataEntry
	0, // 2: broadcast.BroadcastService.BroadcastAction:input_type -> broadcast.BroadcastActionRequest
	2, // 3: broadcast.BroadcastService.SubscribeToActions:input_type -> broadcast.SubscribeRequest
	1, // 4: broadcast.BroadcastService.BroadcastAction:output_type -> broadcast.BroadcastActionResponse
	3, // 5: broadcast.BroadcastService.SubscribeToActions:output_type -> broadcast.ActionSummary
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_protos_broadcast_broadcast_proto_init() }
func file_api_protos_broadcast_broadcast_proto_init() {
	if File_api_protos_broadcast_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_broadcast_broadcast_proto_rawDesc), len(file_api_protos_broadcast_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_broadcast_broadcast_proto_goTypes,
		DependencyIndexes: file_api_protos_broadcast_broadcast_proto_depIdxs,
		MessageInfos:      file_api_protos_broadcast_broadcast_proto_msgTypes,
	}.Build()
	File_api_protos_broadcast_broadcast_proto = out.File
	file_api_protos_broadcast_broadcast_proto_goTypes = nil
	file_api_protos_broadcast_broadcast_proto_depIdxs = nil
}
